### PR TITLE
[help wanted] Implement file search

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**
Implements file search as part of #333

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
As the search page isn't derived from BaseLayout, I had to duplicate some of the functionality.

**Comment by yaichenbaum** [comment]
I think we should hold off on this for now as we haven't published any specs on how search should work.

**Comment by Jaiganeshkumaran** [comment]
Okay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by yaichenbaum** [comment]
- Quick search results should show in a drop down under the search box.
- Pressing enter on the search box should go to the search page and show more results.
- Search results should include sub directories by default.

**Comment by Jaiganeshkumaran** [comment]
Should the Quick search drop down show files in subfolders?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yaichenbaum** [comment]
> Should the Quick search drop down show files in subfolders?

By default it should, I think providing an option for this would be useful but it shouldn't be necessary for the initial version.

**Comment by Jaiganeshkumaran** [comment]
What about small window sizes? Should clicking the search button open the search page or should it popup the quick search box.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jaiganeshkumaran** [comment]
Is Search needed for Recycle bin?

**Comment by Jaiganeshkumaran** [comment]
After searching once, files are no longer loading. I get this message in the debug output. `onecore\com\combase\dcomrem\preventrundownbias.cpp(1310)\combase.dll!76338936: (caller: 763386D6) LogHr(108) tid(2618) 80070005 Access is denied.` 
I think the WinRT Search API is messing with the Win32 Filesystem APIs. In that case, we may need to implement search by ourselves.

**Comment by Jaiganeshkumaran** [comment]
It seems that this error occurs when there's no permission to access the file system. I've given access to  filesystem but it isn't working.

**Comment by Jaiganeshkumaran** [comment]
I'm closing this pull request for now since we have many bugs that needs to fixed. I'll reopen this later.

**Pull request closed without merging**
