### PR TITLE
Add Private Network capability for proper NAS drive support

### LINKED ISSUE #642: Network folders appear empty, but it works in Files UWP - Dev
In "files uwp - dev", the contents of the network locations are displayed correctly, however in the microsoft store version they appear empty.

**Update:** network locations still appear empty (v0.10.2)

80325018-82dba900-8801-11ea-8d3c-4ab8fa5cb31d

### PR DESCRIPTION
**Pull request by duke7553**
Fixes #642

### CODE REVIEW

**Comment by duke7553** [comment]
Hopefully, this does the trick. Please test this branch and let us know!

**Comment by yaichenbaum** [comment]
cc @XPoppyX

**Comment by XPoppyX** [comment]
packaging for testing...

**Comment by duke7553** [comment]
@XPoppyX Thank you. That way, others can test easily

**Comment by XPoppyX** [comment]
from my side, network drives still appearing empty

**Comment by duke7553** [comment]
@XPoppyX Thanks for spotting this again.

Is the network public or private in Windows?

**Comment by XPoppyX** [comment]
private

**Comment by duke7553** [comment]
@XPoppyX Did you package the app first, or install from VS?

**Comment by XPoppyX** [comment]
I packed it, because this bug happens only if it's packaged

**Comment by gave92** [comment]
@duke7553 `FindFirstFileExFromApp` apparently return `-1` when accessing a network location from a packaged app.
If you don't find a better way, the method of enumerating folder contents I'm using for MTP devices in #926 seems to work for network locations, even when the app is packaged.

**Comment by duke7553** [comment]
@gave92 Yeah, I noticed that! 

I wonder if it has to do with flags being set for the Find operation?

**Comment by duke7553** [comment]
@gave92 Are users able to manually enter the path to the mapped network drive when the app is packaged?

**Comment by gave92** [comment]
@duke Do you mean in #926? Yes they can

**Pull request closed without merging**
