### PR TITLE
Add connected animations for opening folder in new tab

### PR DESCRIPTION
**Pull request by hez2010**
User experience improvements:

- Add connected animations for opening folder in new tab

Screen recording:

### CODE REVIEW

**Comment by soumyamahunt** [comment]
Would be better if the animation happens only once for opening multiple folders.

**Comment by hez2010** [comment]
@soumyamahunt 
I tried but failed to figure out a way to start multiple animations simultaneously :(
ConnectedAnimation doesn't take effects if there's other on-going ConnectedAnimation.

**Comment by yaichenbaum** [comment]
@hez2010 Will this affect the horizontal tab strip when it's enabled?

**Comment by hez2010** [comment]
I will rebase this PR and add support for the horizontal tab.

**Comment by yaichenbaum** [comment]
@hez2010 I am going to close this pull request as there has been no activity for at least 7 days, please reopen it when you get a chance to add support for horizontal tabs.

**Pull request closed without merging**
