### PR TITLE
Updated Nuget packages

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by gave92** [comment]
I'm seeing that I mistakenly added the `Microsoft.Net.Compilers` dependency. I needed that to build the project with Visual Studio 2017. You have no reason to keep it. I apologize.

**Comment by yaichenbaum** [comment]
@gave92 Can you remove that in a separate pull request?

**Comment by gave92** [comment]
Ok I'll do that

**Comment by yaichenbaum** [comment]
@gave92 Thank you.

**Pull request merged**
