### PR TITLE
[TO BE TESTED] - (Maybe) fix recycle bin menu opening in standard folder (#1283)

### LINKED ISSUE #1283: Recycle bin menu opens for current tab(not recycle bin) if Recycle bin is opened in another tab
**To Reproduce**
1. Open any folder in one tab
2. Open Recycle bin in another tab
3. Right click on empty space in Recycle bin tab
4. Right click on empty space in first tab in regular folder
5. Recycle bin context menu appears

**Expected behavior**
Expected to be opened normal context menu for folder.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

### PR DESCRIPTION
**Pull request by gave92**
PR to test a fix #1283.
@tsvietOK I'll need your help (as usual 😁) to test if this solves the issue.

### CODE REVIEW

**Comment by tsvietOK** [comment]
Sorry, but i can't reproduce this issue anymore.

**Comment by gave92** [comment]
@tsvietOK It's ok, I was getting this veery rarely too.
Perhaps @Jaiganeshkumaran according to #1305 you were you having this issue as well? Are you able to repro this with any consistency and check if this PR helps?

**Comment by tsvietOK** [comment]
Closing this PR now as no one can reproduce the issue.

**Comment by gave92** [comment]
@tsvietOK The bug is still present although it appears to be very rare #1483 
Should we reopen this? But I still have no way of testing if this solves the issue as I can't reproduce it consistently :(

**Comment by tsvietOK** [comment]
This PR will be reopened only when someone can consistently reproduce the issue and test fix for it.

**Pull request closed without merging**
