### PR TITLE
Properties: Add support for combined and drive properties

### LINKED ISSUE #259: Refinements to Properties
**Is your feature request related to a problem? Please describe.**
I suggest these refinements to the properties especially useful when comparing folders/files.
Currently I just can see the size of one file but not for folders and or when selecting more than on folder/file.

**Describe the solution you'd like**
I would like to see the overall size of a folder and/or files (and the count of folders and files inside this folder).

**Describe alternatives you've considered**
Also when choosing more than one file and/or folder, I would like to see the count of files and the overall size.

**Additional context**
This is how it is handled in file explorer:
image

### PR DESCRIPTION
**Pull request by tsvietOK**
New combined properties:
image
New drive properties:
image
Thanks: #1097 
Fixes #259

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Will this fix #876?

**Comment by tsvietOK** [comment]
@Jaiganeshkumaran It will not show dates for drive properties at all.

**Comment by XPoppyX** [comment]
is it possible to add the "Disk cleanup" option?

**Comment by yaichenbaum** [comment]
@XPoppyX Being that Disk Cleanup is being deprecated in favor of Storage Sense, it would make sense to keep along the same path for Files UWP.

**Comment by XPoppyX** [comment]
on all my disks the type shows as "fixed", what does it mean?

**Comment by Jaiganeshkumaran** [comment]
I think it means that the drive isn’t removable.

**Comment by XPoppyX** [comment]
mm, but it also shows that on my external disk

**Pull request merged**
