### PR TITLE
Update lang FR

### PR DESCRIPTION
**Pull request by boscorelly**

### CODE REVIEW

**Review by yaichenbaum — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@boscorelly Can you resolve the merge conflicts?

**Comment by yaichenbaum** [comment]
@boscorelly It looks like there are still some conflicts.

**Comment by boscorelly** [comment]
i don't know why it's saying this as i have ytzndlzyrf from fresh fork.

and i don't know what to do

**Comment by boscorelly** [comment]
if you know what to do, tell me, it's ennoying :/

**Comment by yaichenbaum** [comment]
@boscorelly Merge the `master` branch into your fork.

**Comment by boscorelly** [comment]
this fu****** tool doesn't want me to do it, it also say there are 
conflicts where there is not.

seriously, i never had this problem before, saying conflics on 100% 
identical files.

**Pull request closed without merging**
