### PR TITLE
pt-BR translation improvements

### PR DESCRIPTION
**Pull request by Suburbanno**
Translations corrections and typos fixes

### CODE REVIEW

**Comment by XPoppyX** [comment]
should be changed from: **state = "new"** to **state = "translated"**

**Comment by Suburbanno** [comment]
state="needs-review-translation" state-qualifier="tm-suggestion"  for  state = "translated"
@XPoppyX too?

**Comment by XPoppyX** [comment]
@Suburbanno yes

**Comment by Suburbanno** [comment]
@XPoppyX thanks!

**Pull request merged**
