### PR TITLE
Some typo and bug fixes

### LINKED ISSUE #1229: Launching terminal profiles from the navigation bar is not working correctly
The expected behavior is to be able to launch any terminal profile from the navigation bar. For example I have a profile for cmd and another one for Terminal. I am only able to launch "wt" from the navigation bar. When I try "cmd", nothing happens.

### PR DESCRIPTION
**Pull request by soumyamahunt**
Fixed #1229 and typo for environment variable.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@soumyamahunt I can still reproduce this issue after merging your changes.

**Comment by soumyamahunt** [comment]
> @soumyamahunt I can still reproduce this issue after merging your changes.

Is it happening to all terminal profiles or specific ones, can you provide which terminal profiles are having issues??

**Comment by yaichenbaum** [comment]
> > @soumyamahunt I can still reproduce this issue after merging your changes.
> 
> Is it happening to all terminal profiles or specific ones, can you provide which terminal profiles are having issues??

I am seeing the issue with all profiles.

**Comment by soumyamahunt** [comment]
> I am seeing the issue with all profiles.

I tried all default profiles and didn't have any issue in them, @duke7553 you having issue with this too??

WGrOqTvtbq

TYIMaCoQs8

aRi0nNsE3h

**Comment by yaichenbaum** [comment]
@soumyamahunt It seems to be working fine now.

**Pull request merged**
