### PR TITLE
Added pin path to sidebar to right click context menu

### LINKED ISSUE #255: Add option to right click context menu to pin the current directory to the sidebar
**Is your feature request related to a problem? Please describe.**
I want to add a whole smb-server to the sidebar. Since the network address section isn't shown, I cannot view network addresses and therefore pin e.g. whole SMB-servers through right click to the sidebar. (e.g. such addresses: **\\\smb-server**)

**Describe the solution you'd like**
Please enable us to pin the current path to the sidebar.

**Describe alternatives you've considered**
Maybe right-clicking on the current path (or anywhere inside the current folder) and showing the option to pin the current path to the sidebar could be the UX for that. In the file explorer you can do this through pulling the current path into the sidebar section.

### PR DESCRIPTION
**Pull request by yaichenbaum**
Closes #255.

### CODE REVIEW

**Comment by XPoppyX** [comment]
Wouldn't it be better if it were between "refresh and "paste"?
Captura de pantalla (26)

**Comment by yaichenbaum** [comment]
@XPoppyX I haven't thought about that, do you have any reason why it would be better higher up?

**Comment by XPoppyX** [comment]
I think "properties" should always be the last. it is not entirely necessary to put it between "refresh" and "paste", above "properties" is fine too, that depends on you, but it definitely shouldn't be under "properties"

**Comment by yaichenbaum** [comment]
@XPoppyX I don't think moving the location will be an issue, is this something you are interested in working on?

**Comment by XPoppyX** [comment]
in the context menu of folders, "pin to sidebar" is above "properties", just put them in the same way and it will be fine

**Pull request merged**
