### PR TITLE
Update lang fr-FR

### PR DESCRIPTION
**Pull request by boscorelly**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@boscorelly The correct place to translate the strings is in the xlf file.

**Comment by boscorelly** [comment]
Hi,

can you tell me where this place is ? :)

**Comment by Jaiganeshkumaran** [comment]
> Hi, can you tell me where this place is ? :)
Under the MultilingualResources folder. You can use the free [Multilingual app toolkit editor](https://developer.microsoft.com/en-us/windows/downloads/multilingual-app-toolkit/) to edit the file.

**Comment by yaichenbaum** [comment]
@boscorelly Thank you for taking the time to create this pull request, I am going to be closing it as it's been inactive for some time. Please reopen it when you get a chance to address the requested changes.

**Pull request closed without merging**
