### PR TITLE
Update CDRom icon

### LINKED ISSUE #1418: DVD/CD Drives has a Bluetooth icon
**Describe the bug**
As shown in the picture below, the DVD/CD drive has a bluetooth icon

**To Reproduce**
Just open the app and see the sidebar

**Expected behavior**
It should actually be a disc icon

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.12

### PR DESCRIPTION
**Pull request by XPoppyX**
Fixes #1418 
----------------
Before:
Anotación 2020-07-13 085823

After: 
Anotación 2020-07-13 085913

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
This icon should also appear in the tab item. Currently, it displays the generic drive icon even for CD or DVD drive.

**Comment by Jaiganeshkumaran** [comment]
This icon should also appear in the tab item. Currently, it displays the generic drive icon even for CD or DVD drive.

**Comment by XPoppyX** [comment]
@Jaiganeshkumaran this is the problem i guess, i dont know how to fix it
Anotación 2020-07-13 093254

**Comment by Jaiganeshkumaran** [comment]
Checking this is way not the best since you can assign any drive letter to any drive type. Instead find the drive from AppSettings.DriveManager.Drives and set the icon accordingly.

**Pull request merged**
