### PR TITLE
Replaced Segoe MDL2 Assets with Fluent UI icons

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by XPoppyX** [comment]
I edited an icon for: "Invert Selection"
Captura de pantalla (43)

**Comment by duke7553** [comment]
@XPoppyX Hey Richard, please add this icon in another PR to the FluentIcons branch. Thanks!

**Comment by d2dyno1** [comment]
Where can I find spreedsheet of these icons and codes?

**Comment by yaichenbaum** [comment]
@d2dyno1 You can find the codes by opening the FluentUI font in Character Map UWP.

**Pull request merged**
