### PR TITLE
RecycleBin: Remove Properties menu item for the folder itself

### LINKED ISSUE #1263: Properties window not working for recycle bin
**Describe the bug**
Properties option isn't working for the recycle bin. This only occurs for the folder itself and not deleted files on it.

**To Reproduce**
1. Enable recycle bin support
2. Navigate to recycle bin
3. Right-click and hit navigate
4. Files UWP will crash 

**Expected behavior**
It should show the properties of the recycle bin.

**Desktop:**
 - OS Version: Windows 10 Insider Preview Build 20152.1000
 - App version: v0.11.0

### PR DESCRIPTION
**Pull request by tsvietOK**
Fixes #1263

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Instead of removing it, why not modify it? File Explorer does show a properties option for Recycle bin however it opens a completely different dialog.

**Comment by tsvietOK** [comment]
Because for the moment we are don't support showing properties dialog of this type. Maybe in the future when this specific type of dialog will be implemented, we could bring back this menu item.

**Comment by gave92** [comment]
Aw come on it's not so bad.
Size and Number of items is correct!

image

**Comment by XPoppyX** [comment]
but still need changes, half of the displayed properties are useless

**Pull request merged**
