### PR TITLE
Add margin to folder size progress ring

### PR DESCRIPTION
**Pull request by XPoppyX**
**BEFORE:**
ring-BEFORE

**AFTER:**
ring

### CODE REVIEW

**Comment by duke7553** [comment]
@XPoppyX Hi there. Does this make any visible change? The gifs you posted above don't seem to demonstrate one.

**Comment by XPoppyX** [comment]
in the first gif the progress ring moves the texts that are below, with this PR that is fixed

**Comment by yaichenbaum** [comment]
@XPoppyX Can you resolve the merge conflict?

**Comment by XPoppyX** [comment]
done

**Comment by XPoppyX** [comment]
@yaichenbaum  can you check if the progress ring appears after these changes #1055 ?  because for me it no longer appears

**Comment by tsvietOK** [comment]
@XPoppyX @yaichenbaum That caused by this [PR](https://github.com/files-community/files-uwp/commit/f6a3c01ade0dc624b68fa6aaa8b1ab32e7c0e0a1#diff-2c79fcbc14e5b97131d986e6868b3facR155)

**Comment by XPoppyX** [comment]
@tsvietOK fixed, ty

**Comment by yaichenbaum** [comment]
Wouldn't a progress bar fit better than a progress ring?

**Comment by XPoppyX** [comment]
i think maybe size doesn't need a progress indicator anyway

**Comment by yaichenbaum** [comment]
@XPoppyX For large files, or if you open the properties window when multiple items are selected, calculating the size can take some time and therefore a progress indicator is necessary.

**Comment by yaichenbaum** [comment]
@XPoppyX Can you change it back to a progress bar?

**Comment by duke7553** [comment]
@XPoppyX @yaichenbaum Please keep it as a progress ring. A progress bar would not be suited for this area.

**Comment by XPoppyX** [comment]
this is how it looks:
bar

**Comment by yaichenbaum** [comment]
@XPoppyX Instead of the progress depending separately for each item, it should be the overall progress of the whole operation.

**Comment by XPoppyX** [comment]
@yaichenbaum I don't have enough knowledge to make the necessary changes for that

**Comment by yaichenbaum** [comment]
@XPoppyX No worries.

**Comment by XPoppyX** [comment]
I read that it is possible with RadialProgressBar

**Pull request merged**
