### PR TITLE
Added icons in context menu of the sidebar and "More options" + Custom icon for "New tab" and "Open in new tab"

### PR DESCRIPTION
**Pull request by XPoppyX**
- I also changed the "New window" icon

Captura de pantalla (30)
Captura de pantalla (29)
-----------------------------------------------------------------
New window: Captura de pantalla (36)

Open in new tab (custom): Captura de pantalla (29)

New tab (custom): Captura de pantalla (31)

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@XPoppyX Moving forward we expect all pull requests to be connected to an approved issue in the project board. Since we haven't announced this yet we will skip the requirement for this pull request, but please keep it in mind for the future.

**Comment by XPoppyX** [comment]
you mean first add a feature request or bug before doing a PR?

**Comment by yaichenbaum** [comment]
@XPoppyX Correct, this way we can keep track of who will be working on a feature and avoid duplicate work. It will also prevent someone from working on something only to find out that it doesn't align with our plans and that we will not merge their work. This was work only starts after we approve of the changes. In the case that someone is planning on working on something, they can just ping me so I can approve the issue faster and assign them the task.

**Comment by XPoppyX** [comment]
I understand, I'll keep that in mind next time

**Comment by yaichenbaum** [comment]
@XPoppyX Can you resolve the merge conflict?

**Pull request merged**
