### PR TITLE
Fix incorrect path while upward to root disk

### PR DESCRIPTION
**Pull request by hez2010**
Fix incorrect path while upward to root disk

### CODE REVIEW

**Comment by tsvietOK** [comment]
@hez2010 Can you, please, specify repro steps, when i can get incorrect path while upward to root disk

**Comment by xPoppyx** [comment]
Captura de pantalla (212)

**Comment by tsvietOK** [comment]
This changes fixes a bug, but i think it is better to move it to NormalizePath method like
```csharp
public static string NormalizePath(string path)
        {
            if (path.StartsWith("\\\\"))
            {
                return path.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).ToUpperInvariant();
            }
            else
            {
                if (!path.EndsWith(Path.DirectorySeparatorChar))
                {
                    path += Path.DirectorySeparatorChar;
                }

                return Path.GetFullPath(new Uri(path).LocalPath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .ToUpperInvariant();
            }
        }
```

**Comment by hez2010** [comment]
@tsvietOK 
> This changes fixes a bug, but i think it is better to move it to NormalizePath method like

Done

**Pull request merged**
