### PR TITLE
Added ability to cancel hash computation

### PR DESCRIPTION
**Pull request by hez2010**
- Cancel hash computation after property window closed

### CODE REVIEW

**Comment by lampenlampen** [comment]
I see, that you implemented `IDisposable`. Does the runtime/uwp-framework call `Properties.Dispose()` on a page, if it's implemented?

**Comment by hez2010** [comment]
Added some logic.
`CancellationTokenSource` will finally disposed by GC, but it can also be disposed by calling `Dispose()`

**Comment by lampenlampen** [comment]
Why do we even need to implement it? If the dialog is closed, we can handle it in the unloaded event.

**Comment by hez2010** [comment]
Done.

> If the dialog is closed, we can handle it in the unloaded event.

Sounds reasonable.

**Comment by lampenlampen** [comment]
Okay you still saw my answer ;)

My understanding is either the `unloaded`-event fires or the app crashes, so in both cases we are safe.

In the end i decided you option doesn't harm.

**Pull request merged**
