### PR TITLE
Implemented folder dropdown list for Navigationbar

### PR DESCRIPTION
**Pull request by soumyamahunt**
As requested by @mdtauk, implemented clicking on any path items chevron to get a drop-down list of all folders in that directory:

ewvPDaCFgF

### CODE REVIEW

**Comment by soumyamahunt** [comment]
Only thing remaining is Windows Explorer style split-revael-brush.

explorer_qSKvl9ohUL (2)

I am currently working on it but so far what I have come up with aren't visually appealing.

**Comment by soumyamahunt** [comment]
The best I could come up with:

ApplicationFrameHost_gaLOkWFBPr (2)

**Comment by Jaiganeshkumaran** [comment]
@soumyamahunt Which issue was this feature proposed?

**Comment by soumyamahunt** [comment]
> @soumyamahunt Which issue was this feature proposed?

Not in any issue, a user asked me about implementing this feature, which is available in Windows Explorer.

**Comment by Jaiganeshkumaran** [comment]
@soumyamahunt Whenever you are opening a PR in the repository make sure that there's an issue associated with it. If there is no issue, create one before starting a PR.

**Comment by duke7553** [comment]
@soumyamahunt Great work! 

Maybe we can add a MaxHeight to the drop downs?

**Pull request merged**
