### PR TITLE
Updated TabView design

### PR DESCRIPTION
**Pull request by soumyamahunt**
## 1. Removed header padding

ApplicationFrameHost_o10PyVrORP

## 2. Changed TabScrollButton style

yaE6gvbp4Y

## 3. Changed TabCloseButton style

EbmYexSom8

### CODE REVIEW

**Comment by mdtauk** [comment]
Does removing the small gap interfere with people dragging the top edge to resize?  The Double Tap to maximize?  And touch manipulations?

**Comment by soumyamahunt** [comment]
> Does removing the small gap interfere with people dragging the top edge to resize? The Double Tap to maximize? And touch manipulations?

No, removing the small gap doesn't interfere with dragging the top edge to resize, the Double Tap to maximize and touch manipulations. After changing the title bar by `Window.Current.SetTitleBar(AppTitleBar)` only `AppTitleBar` acts as titlebar, so you have to use that element to resize, maximize or minimize etc.

**Comment by yaichenbaum** [comment]
Closing as this change is not connected to an approved issue.

**Comment by yaichenbaum** [comment]
@soumyamahunt Thank you for your pull request, we have some changes in the works that will solve many of the issue of the TabView.

**Pull request closed without merging**
